-- Databricks notebook source
-- DBTITLE 1,履歴データを格納するDB情報
-- MAGIC %sql
-- MAGIC use catalog main;
-- MAGIC
-- MAGIC CREATE DATABASE IF NOT EXISTS KYOTEI_DB;
-- MAGIC use kyotei_db;

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS BANGUMI
(
RACEDATE        string,
PLACE   string,
RACE    string,
PLAYERID1       string,
PLAYERID2       string,
PLAYERID3       string,
PLAYERID4       string,
PLAYERID5       string,
PLAYERID6       string,
CLASS1  string,
CLASS2  string,
CLASS3  string,
CLASS4  string,
CLASS5  string,
CLASS6  string,
CLUB1   string,
CLUB2   string,
CLUB3   string,
CLUB4   string,
CLUB5   string,
CLUB6   string,
AGE1    string,
AGE2    string,
AGE3    string,
AGE4    string,
AGE5    string,
AGE6    string,
WEIGHT1 string,
WEIGHT2 string,
WEIGHT3 string,
WEIGHT4 string,
WEIGHT5 string,
WEIGHT6 string,
F1      string,
F2      string,
F3      string,
F4      string,
F5      string,
F6      string,
L1      string,
L2      string,
L3      string,
L4      string,
L5      string,
L6      string,
WIN1RATE1       string,
WIN1RATE2       string,
WIN1RATE3       string,
WIN1RATE4       string,
WIN1RATE5       string,
WIN1RATE6       string,
WIN2RATE1       string,
WIN2RATE2       string,
WIN2RATE3       string,
WIN2RATE4       string,
WIN2RATE5       string,
WIN2RATE6       string,
WIN3RATE1       string,
WIN3RATE2       string,
WIN3RATE3       string,
WIN3RATE4       string,
WIN3RATE5       string,
WIN3RATE6       string,
LOCALWIN1RATE1  string,
LOCALWIN1RATE2  string,
LOCALWIN1RATE3  string,
LOCALWIN1RATE4  string,
LOCALWIN1RATE5  string,
LOCALWIN1RATE6  string,
LOCALWIN2RATE1  string,
LOCALWIN2RATE2  string,
LOCALWIN2RATE3  string,
LOCALWIN2RATE4  string,
LOCALWIN2RATE5  string,
LOCALWIN2RATE6  string,
LOCALWIN3RATE1  string,
LOCALWIN3RATE2  string,
LOCALWIN3RATE3  string,
LOCALWIN3RATE4  string,
LOCALWIN3RATE5  string,
LOCALWIN3RATE6  string,
MOTORWIN2RATE1  string,
MOTORWIN2RATE2  string,
MOTORWIN2RATE3  string,
MOTORWIN2RATE4  string,
MOTORWIN2RATE5  string,
MOTORWIN2RATE6  string,
MOTORWIN3RATE1  string,
MOTORWIN3RATE2  string,
MOTORWIN3RATE3  string,
MOTORWIN3RATE4  string,
MOTORWIN3RATE5  string,
MOTORWIN3RATE6  string,
BOATWIN2RATE1   string,
BOATWIN2RATE2   string,
BOATWIN2RATE3   string,
BOATWIN2RATE4   string,
BOATWIN2RATE5   string,
BOATWIN2RATE6   string,
BOATWIN3RATE1   string,
BOATWIN3RATE2   string,
BOATWIN3RATE3   string,
BOATWIN3RATE4   string,
BOATWIN3RATE5   string,
BOATWIN3RATE6   string,
ST_AVG1 string,
ST_AVG2 string,
ST_AVG3 string,
ST_AVG4 string,
ST_AVG5 string,
ST_AVG6 string
);

-- COMMAND ----------

ALTER TABLE BANGUMI ALTER COLUMN RACEDATE COMMENT "レース開催日";
ALTER TABLE BANGUMI ALTER COLUMN PLACE COMMENT "レース開催地の名称";
ALTER TABLE BANGUMI ALTER COLUMN RACE COMMENT "レース番号";
ALTER TABLE BANGUMI ALTER COLUMN PLAYERID1 COMMENT "１号艇のレーサーID";
ALTER TABLE BANGUMI ALTER COLUMN PLAYERID2 COMMENT "２号艇のレーサーID";
ALTER TABLE BANGUMI ALTER COLUMN PLAYERID3 COMMENT "３号艇のレーサーID";
ALTER TABLE BANGUMI ALTER COLUMN PLAYERID4 COMMENT "4号艇のレーサーID";
ALTER TABLE BANGUMI ALTER COLUMN PLAYERID5 COMMENT "５号艇のレーサーID";
ALTER TABLE BANGUMI ALTER COLUMN PLAYERID6 COMMENT "６号艇のレーサーID";
ALTER TABLE BANGUMI ALTER COLUMN CLASS1 COMMENT "１号艇のレーサーグレード（A1:400,A2:300,B1:200,B2:100)";
ALTER TABLE BANGUMI ALTER COLUMN CLASS2 COMMENT "2号艇のレーサーグレード（A1:400,A2:300,B1:200,B2:100)";
ALTER TABLE BANGUMI ALTER COLUMN CLASS3 COMMENT "3号艇のレーサーグレード（A1:400,A2:300,B1:200,B2:100)";
ALTER TABLE BANGUMI ALTER COLUMN CLASS4 COMMENT "4号艇のレーサーグレード（A1:400,A2:300,B1:200,B2:100)";
ALTER TABLE BANGUMI ALTER COLUMN CLASS5 COMMENT "5号艇のレーサーグレード（A1:400,A2:300,B1:200,B2:100)";
ALTER TABLE BANGUMI ALTER COLUMN CLASS6 COMMENT "6号艇のレーサーグレード（A1:400,A2:300,B1:200,B2:100)";
ALTER TABLE BANGUMI ALTER COLUMN CLUB1 COMMENT "１号艇のレーサー所属地";
ALTER TABLE BANGUMI ALTER COLUMN CLUB2 COMMENT "２号艇のレーサー所属地";
ALTER TABLE BANGUMI ALTER COLUMN CLUB3 COMMENT "３号艇のレーサー所属地";
ALTER TABLE BANGUMI ALTER COLUMN CLUB4 COMMENT "４号艇のレーサー所属地";
ALTER TABLE BANGUMI ALTER COLUMN CLUB5 COMMENT "５号艇のレーサー所属地";
ALTER TABLE BANGUMI ALTER COLUMN CLUB6 COMMENT "６号艇のレーサー所属地";
ALTER TABLE BANGUMI ALTER COLUMN AGE1 COMMENT "１号艇レーサーの年齢";
ALTER TABLE BANGUMI ALTER COLUMN AGE2 COMMENT "２号艇レーサーの年齢";
ALTER TABLE BANGUMI ALTER COLUMN AGE3 COMMENT "３号艇レーサーの年齢";
ALTER TABLE BANGUMI ALTER COLUMN AGE4 COMMENT "４号艇レーサーの年齢";
ALTER TABLE BANGUMI ALTER COLUMN AGE5 COMMENT "５号艇レーサーの年齢";
ALTER TABLE BANGUMI ALTER COLUMN AGE6 COMMENT "６号艇レーサーの年齢";
ALTER TABLE BANGUMI ALTER COLUMN WEIGHT1 COMMENT "１号艇レーサーの体重";
ALTER TABLE BANGUMI ALTER COLUMN WEIGHT2 COMMENT "２号艇レーサーの体重";
ALTER TABLE BANGUMI ALTER COLUMN WEIGHT3 COMMENT "３号艇レーサーの体重";
ALTER TABLE BANGUMI ALTER COLUMN WEIGHT4 COMMENT "４号艇レーサーの体重";
ALTER TABLE BANGUMI ALTER COLUMN WEIGHT5 COMMENT "５号艇レーサーの体重";
ALTER TABLE BANGUMI ALTER COLUMN WEIGHT6 COMMENT "６号艇レーサーの体重";
ALTER TABLE BANGUMI ALTER COLUMN F1 COMMENT "１号艇レーサーのスタートフライング回数";
ALTER TABLE BANGUMI ALTER COLUMN F2 COMMENT "２号艇レーサーのスタートフライング回数";
ALTER TABLE BANGUMI ALTER COLUMN F3 COMMENT "３号艇レーサーのスタートフライング回数";
ALTER TABLE BANGUMI ALTER COLUMN F4 COMMENT "４号艇レーサーのスタートフライング回数";
ALTER TABLE BANGUMI ALTER COLUMN F5 COMMENT "５号艇レーサーのスタートフライング回数";
ALTER TABLE BANGUMI ALTER COLUMN F6 COMMENT "６号艇レーサーのスタートフライング回数";
ALTER TABLE BANGUMI ALTER COLUMN L1 COMMENT "１号艇レーサーのスタート遅れ回数";
ALTER TABLE BANGUMI ALTER COLUMN L2 COMMENT "２号艇レーサーのスタート遅れ回数";
ALTER TABLE BANGUMI ALTER COLUMN L3 COMMENT "３号艇レーサーのスタート遅れ回数";
ALTER TABLE BANGUMI ALTER COLUMN L4 COMMENT "４号艇レーサーのスタート遅れ回数";
ALTER TABLE BANGUMI ALTER COLUMN L5 COMMENT "５号艇レーサーのスタート遅れ回数";
ALTER TABLE BANGUMI ALTER COLUMN L6 COMMENT "６号艇レーサーのスタート遅れ回数";
ALTER TABLE BANGUMI ALTER COLUMN WIN1RATE1 COMMENT "１号艇レーサーの全レース場での１着勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN1RATE2 COMMENT "２号艇レーサーの全レース場での１着勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN1RATE3 COMMENT "３号艇レーサーの全レース場での１着勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN1RATE4 COMMENT "４号艇レーサーの全レース場での１着勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN1RATE5 COMMENT "５号艇レーサーの全レース場での１着勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN1RATE6 COMMENT "６号艇レーサーの全レース場での１着勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN2RATE1 COMMENT "１号艇レーサーの全レース場での２着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN2RATE2 COMMENT "２号艇レーサーの全レース場での２着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN2RATE3 COMMENT "３号艇レーサーの全レース場での２着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN2RATE4 COMMENT "４号艇レーサーの全レース場での２着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN2RATE5 COMMENT "５号艇レーサーの全レース場での２着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN2RATE6 COMMENT "６号艇レーサーの全レース場での２着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN3RATE1 COMMENT "１号艇レーサーの全レース場での３着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN3RATE2 COMMENT "２号艇レーサーの全レース場での３着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN3RATE3 COMMENT "３号艇レーサーの全レース場での３着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN3RATE4 COMMENT "４号艇レーサーの全レース場での３着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN3RATE5 COMMENT "５号艇レーサーの全レース場での３着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN WIN3RATE6 COMMENT "６号艇レーサーの全レース場での３着以内勝率（過去６ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN1RATE1 COMMENT "１号艇レーサーのレース開催地レース場での１着勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN1RATE2 COMMENT "２号艇レーサーのレース開催地レース場での１着勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN1RATE3 COMMENT "３号艇レーサーのレース開催地レース場での１着勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN1RATE4 COMMENT "４号艇レーサーのレース開催地レース場での１着勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN1RATE5 COMMENT "５号艇レーサーのレース開催地レース場での１着勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN1RATE6 COMMENT "６号艇レーサーのレース開催地レース場での１着勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN2RATE1 COMMENT "１号艇レーサーのレース開催地レース場での２着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN2RATE2 COMMENT "２号艇レーサーのレース開催地レース場での２着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN2RATE3 COMMENT "３号艇レーサーのレース開催地レース場での２着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN2RATE4 COMMENT "４号艇レーサーのレース開催地レース場での２着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN2RATE5 COMMENT "５号艇レーサーのレース開催地レース場での２着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN2RATE6 COMMENT "６号艇レーサーのレース開催地レース場での２着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN3RATE1 COMMENT "１号艇レーサーのレース開催地レース場での３着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN3RATE2 COMMENT "２号艇レーサーのレース開催地レース場での３着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN3RATE3 COMMENT "３号艇レーサーのレース開催地レース場での３着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN3RATE4 COMMENT "４号艇レーサーのレース開催地レース場での３着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN3RATE5 COMMENT "５号艇レーサーのレース開催地レース場での３着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN LOCALWIN3RATE6 COMMENT "６号艇レーサーのレース開催地レース場での３着以内勝率（過去２４ヶ月以内）";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN2RATE1 COMMENT "１号艇のモーター２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN2RATE2 COMMENT "２号艇のモーター２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN2RATE3 COMMENT "３号艇のモーター２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN2RATE4 COMMENT "４号艇のモーター２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN2RATE5 COMMENT "５号艇のモーター２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN2RATE6 COMMENT "６号艇のモーター２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN3RATE1 COMMENT "１号艇のモーター３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN3RATE2 COMMENT "２号艇のモーター３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN3RATE3 COMMENT "３号艇のモーター３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN3RATE4 COMMENT "４号艇のモーター３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN3RATE5 COMMENT "５号艇のモーター３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN MOTORWIN3RATE6 COMMENT "６号艇のモーター３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN2RATE1 COMMENT "１号艇のボート２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN2RATE2 COMMENT "２号艇のボート２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN2RATE3 COMMENT "３号艇のボート２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN2RATE4 COMMENT "４号艇のボート２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN2RATE5 COMMENT "５号艇のボート２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN2RATE6 COMMENT "６号艇のボート２着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN3RATE1 COMMENT "１号艇のボート３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN3RATE2 COMMENT "2号艇のボート３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN3RATE3 COMMENT "3号艇のボート３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN3RATE4 COMMENT "4号艇のボート３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN3RATE5 COMMENT "5号艇のボート３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN BOATWIN3RATE6 COMMENT "6号艇のボート３着以内勝率";
ALTER TABLE BANGUMI ALTER COLUMN ST_AVG1 COMMENT "１号艇レーサーのスタートタイミング（０に近いほど良い）";
ALTER TABLE BANGUMI ALTER COLUMN ST_AVG2 COMMENT "２号艇レーサーのスタートタイミング（０に近いほど良い）";
ALTER TABLE BANGUMI ALTER COLUMN ST_AVG3 COMMENT "３号艇レーサーのスタートタイミング（０に近いほど良い）";
ALTER TABLE BANGUMI ALTER COLUMN ST_AVG4 COMMENT "４号艇レーサーのスタートタイミング（０に近いほど良い）";
ALTER TABLE BANGUMI ALTER COLUMN ST_AVG5 COMMENT "５号艇レーサーのスタートタイミング（０に近いほど良い）";
ALTER TABLE BANGUMI ALTER COLUMN ST_AVG6 COMMENT "６号艇レーサーのスタートタイミング（０に近いほど良い）";


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS RESULT
(
RACEDATE        string,
PLACE   string,
RACE    string,
RENTAN3 string,
RENTAN3K        string,
RENFUKU3        string,
RENFUKU3K       string,
RENTAN2         string,
RENTAN2K        string,
RENFUKU2        string,
RENFUKU2K       string,
WIDE1   string,
WIDE1K  string,
WIDE2   string,
WIDE2K  string,
WIDE3   string,
WIDE3K  string,
TAN     string,
TANK    string,
FUKU1   string,
FUKU1K  string,
FUKU2   string,
FUKU2K  string,
EOL     string
);

-- COMMAND ----------

ALTER TABLE RESULT ALTER COLUMN RACEDATE COMMENT "レース開催日";
ALTER TABLE RESULT ALTER COLUMN PLACE COMMENT "レース開催地の名称";
ALTER TABLE RESULT ALTER COLUMN RACE COMMENT "レース番号";

ALTER TABLE RESULT ALTER COLUMN RENTAN3 COMMENT "３連単";
ALTER TABLE RESULT ALTER COLUMN RENTAN3K COMMENT "3連単払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN RENFUKU3 COMMENT "３連複";
ALTER TABLE RESULT ALTER COLUMN RENFUKU3K COMMENT "3連複払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN RENTAN2 COMMENT "２連単";
ALTER TABLE RESULT ALTER COLUMN RENTAN2K COMMENT "２連単払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN RENFUKU2 COMMENT "２連複";
ALTER TABLE RESULT ALTER COLUMN RENFUKU2K COMMENT "２連複払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN WIDE1 COMMENT "拡連複１";
ALTER TABLE RESULT ALTER COLUMN WIDE1K COMMENT "拡連複１払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN WIDE2 COMMENT "拡連複２";
ALTER TABLE RESULT ALTER COLUMN WIDE2K COMMENT "拡連複２払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN WIDE3 COMMENT "拡連複３";
ALTER TABLE RESULT ALTER COLUMN WIDE3K COMMENT "拡連複３払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN TAN COMMENT "単勝";
ALTER TABLE RESULT ALTER COLUMN TANK COMMENT "単勝払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN FUKU1 COMMENT "複勝１";
ALTER TABLE RESULT ALTER COLUMN FUKU1K COMMENT "複勝１払い戻し金額";
ALTER TABLE RESULT ALTER COLUMN FUKU2 COMMENT "複勝２";
ALTER TABLE RESULT ALTER COLUMN FUKU2K COMMENT "複勝２払い戻し金額";
